### ISSUE TITLE
Azure technologies for twitter

### ISSUE THREAD

**Issue by davidvaldez89d** [KNobles/earthquake-prediction#4]

**Comment by davidvaldez89d** [comment]
Research azure services
https://azure.microsoft.com/en-us/products/databricks/
https://github.com/Azure-Samples/twitter-databricks-analyzer-cicd

**Comment by AVanneste** [comment]
https://medium.com/@adilsonbna/twitter-sentiment-analysis-using-azure-databricks-1ddba8a96c13

**Comment by davidvaldez89d** [comment]
https://karthi-net.medium.com/build-real-time-twitter-dashboard-using-azure-logicapps-power-bi-811788c83d37

https://koukia.ca/azure-logic-app-to-publish-covid19-developments-on-twitter-be8616432e5a

https://analystcave.com/how-to-create-a-twitter-power-bi-dashboard-with-azure/

https://powerbi.microsoft.com/it-it/blog/visualize-big-data-with-power-bi-and-spark-for-azure-hdinsight/

https://www.researchgate.net/publication/277763583_Twitter_earthquake_detection_Earthquake_monitoring_in_a_social_world

https://digital.gov/2015/06/26/tweets-earthquakes/

https://www.livescience.com/45385-earthquake-alerts-from-twitter.html

https://myshake.berkeley.edu/
